const topics = [
  ['penguin', 'ice', 'polarExpress', 'iceBear', 'snow'],
  ['playground', 'swing', 'slide', 'seesaw', 'child'],
  ['pizza', 'cheese', 'pepperoni', 'dough', 'sauce'],
  ['space', 'rocket', 'planet', 'alien', 'starship'],
  ['underwater', 'fish', 'bubble', 'coral', 'ocean'],
  ['jungle', 'monkey', 'banana', 'tree', 'vines'],
  ['kitchen', 'spoon', 'pot', 'chef', 'recipe'],
  ['circus', 'clown', 'balloon', 'tent', 'acrobat'],
  ['farm', 'cow', 'tractor', 'hay', 'barn'],
  ['castle', 'dragon', 'knight', 'sword', 'princess'],
  ['beach', 'sand', 'wave', 'shell', 'surfboard'],
  ['forest', 'mushroom', 'fairy', 'tree', 'path'],
  ['school', 'pencil', 'book', 'teacher', 'homework'],
  ['party', 'balloon', 'cake', 'music', 'dance'],
  ['magic', 'wand', 'spell', 'wizard', 'crystal'],
  ['robot', 'gear', 'circuit', 'metal', 'battery'],
  ['garden', 'flower', 'butterfly', 'soil', 'seed'],
  ['library', 'book', 'page', 'librarian', 'shelf'],
  ['bakery', 'bread', 'flour', 'oven', 'cookie'],
  ['zoo', 'animal', 'cage', 'keeper', 'visitor'],
  ['theater', 'stage', 'actor', 'curtain', 'spotlight'],
  ['hospital', 'doctor', 'medicine', 'patient', 'bed'],
  ['airport', 'plane', 'pilot', 'luggage', 'ticket'],
  ['museum', 'art', 'painting', 'sculpture', 'gallery'],
  ['carnival', 'ride', 'ticket', 'prize', 'game'],
  ['aquarium', 'fish', 'tank', 'water', 'glass'],
  ['observatory', 'telescope', 'star', 'planet', 'night'],
  ['windmill', 'wind', 'blade', 'energy', 'field'],
  ['lighthouse', 'light', 'coast', 'ship', 'tower'],
  ['volcano', 'lava', 'fire', 'mountain', 'eruption'],
  ['desert', 'cactus', 'sand', 'camel', 'oasis'],
  ['tundra', 'ice', 'wolf', 'aurora', 'cold'],
  ['savanna', 'lion', 'grass', 'gazelle', 'sun'],
  ['rainforest', 'parrot', 'vine', 'waterfall', 'humidity'],
  // 10 more fun topic collections
  ['ninja', 'shuriken', 'katana', 'stealth', 'shadow'],
  ['pirate', 'treasure', 'ship', 'parrot', 'gold'],
  ['superhero', 'cape', 'mask', 'powers', 'villain'],
  ['wizard', 'spellbook', 'staff', 'magic', 'crystal'],
  ['detective', 'magnifying', 'clue', 'mystery', 'suspect'],
  ['astronaut', 'spacesuit', 'moon', 'gravity', 'orbit'],
  ['cowboy', 'horse', 'saddle', 'ranch', 'lasso'],
  ['viking', 'axe', 'helmet', 'longship', 'mead'],
  ['samurai', 'armor', 'bushido', 'honor', 'sword'],
  ['knight', 'shield', 'castle', 'quest', 'dragon'],
];

export default topics;
