const topics = {
  0: [
    ['penguin', 'ice', 'polarExpress', 'iceBear', 'snow'],
    ['playground', 'swing', 'slide', 'seesaw', 'child'],
    ['pizza', 'cheese', 'pepperoni', 'dough', 'sauce'],
    ['kitchen', 'spoon', 'pot', 'chef', 'recipe'],
    ['farm', 'cow', 'tractor', 'hay', 'barn'],
  ],
  1: [
    ['garden', 'flower', 'butterfly', 'soil', 'seed'],
    ['bakery', 'bread', 'flour', 'oven', 'cookie'],
    ['zoo', 'animal', 'cage', 'keeper', 'visitor'],
    ['school', 'pencil', 'book', 'teacher', 'homework'],
    ['party', 'streamer', 'cake', 'music', 'dance'],
    ['beach', 'sand', 'wave', 'shell', 'surfboard'],
    ['forest', 'mushroom', 'fairy', 'oak', 'path'],
    ['library', 'novel', 'page', 'librarian', 'shelf'],
    ['theater', 'stage', 'actor', 'curtain', 'spotlight'],
    ['hospital', 'doctor', 'medicine', 'patient', 'bed'],
    ['airport', 'plane', 'pilot', 'luggage', 'ticket'],
    ['museum', 'art', 'painting', 'sculpture', 'gallery'],
    ['carnival', 'ride', 'pass', 'prize', 'game'],
    ['aquarium', 'guppy', 'tank', 'water', 'glass'],
    ['windmill', 'wind', 'blade', 'energy', 'field'],
  ],
  2: [
    ['space', 'rocket', 'planet', 'alien', 'starship'],
    ['underwater', 'fish', 'bubble', 'coral', 'ocean'],
    ['jungle', 'monkey', 'banana', 'tree', 'vines'],
    ['circus', 'clown', 'balloon', 'tent', 'acrobat'],
    ['castle', 'dragon', 'knight', 'sword', 'princess'],
    ['magic', 'wand', 'spell', 'wizard', 'crystal'],
    ['robot', 'gear', 'circuit', 'metal', 'battery'],
    ['lighthouse', 'light', 'coast', 'ship', 'tower'],
    ['observatory', 'telescope', 'star', 'galaxy', 'night'],
    ['desert', 'cactus', 'dune', 'camel', 'oasis'],
    ['tundra', 'frost', 'wolf', 'aurora', 'cold'],
    ['savanna', 'lion', 'grass', 'gazelle', 'sun'],
    ['rainforest', 'macaw', 'vine', 'waterfall', 'humidity'],
    ['ninja', 'shuriken', 'katana', 'stealth', 'shadow'],
    ['pirate', 'treasure', 'ship', 'parrot', 'gold'],
    ['superhero', 'cape', 'mask', 'powers', 'villain'],
    ['detective', 'magnifying', 'clue', 'mystery', 'suspect'],
    ['astronaut', 'spacesuit', 'moon', 'gravity', 'orbit'],
    ['cowboy', 'horse', 'saddle', 'ranch', 'lasso'],
    ['viking', 'axe', 'helmet', 'longship', 'mead'],
    ['volcano', 'lava', 'fire', 'mountain', 'eruption'],
    ['samurai', 'armor', 'bushido', 'honor', 'katana'],
    ['knight', 'shield', 'fortress', 'quest', 'dragon'],
    ['timeTravel', 'portal', 'chronometer', 'paradox', 'temporal'],
    ['underworld', 'shadow', 'phantom', 'specter', 'ghost'],
    ['spaceStation', 'module', 'airlock', 'gravity', 'orbit'],
    ['wizard', 'spellbook', 'staff', 'enchantment', 'gem'],
    ['nuclear', 'reactor', 'radiation', 'core', 'meltdown', 'containment'],
    ['crimescene', 'evidence', 'detective', 'suspect', 'fingerprint', 'alibi'],
    [
      'naturalDisasters',
      'earthquake',
      'tsunami',
      'hurricane',
      'flood',
      'wildfire',
    ],
  ],
};

export default topics;
